index:
    path: /
    controller: App\Controller\DashboardController::dashboard


# -----------  Publishers routes ----------------------------

PublishersListRoute:
    methods: [GET]
    path: /publishers/list
    controller: App\Controller\PublisherController::getAll

PublisherViewRoute:
    methods: [GET]
    path: /publishers/{id}
    controller: App\Controller\PublisherController::getOne


# -----------  Authors routes ----------------------------

AuthorsListRoute:
    methods: [GET]
    path: /authors/list
    controller: App\Controller\AuthorController::getAll

AuthorViewRoute:
    methods: [GET]
    path: /authors/{id}
    controller: App\Controller\AuthorController::getOne

# -----------  Books routes ----------------------------

BooksHighligthedRoute:
    methods: [GET]
    path: /books/highlighted
    controller: App\Controller\BookController::getAllFeatured

BookViewRoute:
    methods: [GET]
    path: /books/{id}
    controller: App\Controller\BookController::getOne
